### PR TITLE
Fix proper  set result field names  when using join clause

### LINKED ISSUE #137: Nested select statement result set fields unnamed when using join clause
Details in #136 .

### PR DESCRIPTION
**Pull request by gernest**
Closes #137
Context #136

This PR make sure the field names for results nested select are set properly.

Previously the names were set to empty strings .

### CODE REVIEW

File: all_test.go [hunk 1]
```diff
@@ -3501,3 +3502,67 @@ COMMIT;
...
+	}
+	defer rows.Close()
+	c, _ := rows.Columns()
+	e := []string{
+		"product_key",
+		"category_name",
+		"product_condkey",
+		"condition.key",
+		"condition.name"}
+	if !reflect.DeepEqual(e, c) {
```
Comment (cznic) [inline all_test.go]: Feel free to ignore, it's not critical: It's just few lines of non-reflect code that can replace reflect.DeepEqual in this simple case.

**Comment by gernest** [comment]
I rebased this on master and fixed merge conflicts
